### PR TITLE
chore: update and unify dependencies

### PR DESCRIPTION
**Pull request by cehali**

### CODE REVIEW

**Comment by cehali** [comment]
Based on https://github.com/NomicFoundation/hardhat/issues/3877

**Review by koonopek — APPROVED** [review]
Nice!

**Review by hatskier — COMMENTED** [review]
Why does it have so many changes that are not related to deps?

**Comment by cehali** [comment]
> Why does it have so many changes that are not related to deps?

@hatskier Updated dependencies changed their interfaces or removed some functions and I had to resolve those issues. The only change is that waffle within hardhat doesn't allow passing parameters in the `revertedWith` function. I added `.withArgs` to make it work.

**Pull request closed without merging**
